version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: master
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: gradle
    directory: /
    target-branch: master
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      gradle-dependencies:
        patterns:
          - "*"
